version: "3.1"
services:
  app:
    build:
      context: .
    image: springapp:1.1
    ports:
     - "8082:8082"
    depends_on:
     - appMock
    links:
     - appMock
  appMock:
    build:
      context: ./appMock
    image: appmock:1.1
    ports:
     - "8092:8092"