package com.rilussion.alpha;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Application {

    public static void main(String[] args) {

        SpringApplication.run(new Object[] {Application.class},args);
    }
}
