/*
 * This Spock specification was generated by the Gradle 'init' task.
 */

import com.rilussion.alpha.Application
import spock.lang.Specification

class AppTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new Application()

        when:
        def result = app

        then:
        result != null
    }
}
